document.writeln("<style>");
document.writeln("* {");
document.writeln("    margin: 0;");
document.writeln("    padding: 0;");
document.writeln("}");
document.writeln(".footer_service {");
document.writeln("    background: #e0e0e0;");
document.writeln("    margin-top: 50px;");
document.writeln("    padding: 30px 0;");
document.writeln("}");
document.writeln(".service {");
document.writeln("    width: 1200px;");
document.writeln("    margin: 0 auto;");
document.writeln("    overflow: hidden;");
document.writeln("}");
document.writeln(".footer_service li {");
document.writeln("    float: left;");
document.writeln("    width: 190px;");
document.writeln("    height: 42px;");
document.writeln("    margin-left: 55px;");
document.writeln("    padding-left: 55px;");
document.writeln("    background: url(\'./images/footer_service_icon.png\') no-repeat left top;");
document.writeln("    list-style: none;");
document.writeln("}");
document.writeln(".footer_service .s181 {");
document.writeln("    background-position: 0 0;");
document.writeln("}");
document.writeln(".footer_service .s182 {");
document.writeln("    background-position: 0 -42px;");
document.writeln("}");
document.writeln(".footer_service .s183 {");
document.writeln("    background-position: 0 -84px;");
document.writeln("}");
document.writeln(".footer_service .s184 {");
document.writeln("    background-position: 0 -126px;");
document.writeln("}");
document.writeln(".footer_service li b {");
document.writeln("    display: block;");
document.writeln("    padding-left: 15px;");
document.writeln("    color: #007f4d;");
document.writeln("    font: normal 18px/25px \'Microsoft YaHei\';");
document.writeln("    border-left: 1px solid #a6a6a6;");
document.writeln("}");
document.writeln(".footer_service li span {");
document.writeln("    display: block;");
document.writeln("    padding-left: 15px;");
document.writeln("    border-left: 1px solid #a6a6a6;");
document.writeln("    font-size: 12px;");
document.writeln("}");
document.writeln(".footer18_list {");
document.writeln("    width: 1200px;");
document.writeln("    margin: 50px auto 0;");
document.writeln("}");
document.writeln(".footer18 {");
document.writeln("    padding-bottom: 20px;");
document.writeln("    color: #575556;");
document.writeln("    font-size: 12px;");
document.writeln("}");
document.writeln(".footer18 dl {");
document.writeln("    margin-left: 50px;");
document.writeln("    display: inline;");
document.writeln("}");
document.writeln(".footer18 dl {");
document.writeln("    float: left;");
document.writeln("    width: 190px;");
document.writeln("}");
document.writeln(".footer18 dl dt {");
document.writeln("    height: 23px;");
document.writeln("    line-height: 23px;");
document.writeln("    font-size: 14px;");
document.writeln("    text-indent: 40px;");
document.writeln("}");
document.writeln(".col181 dt {");
document.writeln("    background: url(\'./images/footer_icon.png\') no-repeat 0 0;");
document.writeln("}");
document.writeln(".col182 dt {");
document.writeln("    background: url(\'./images/footer_icon.png\') no-repeat  0 -23px;");
document.writeln("}");
document.writeln(".col183 dt {");
document.writeln("    background: url(\'./images/footer_icon.png\') no-repeat  0 -46px;");
document.writeln("}");
document.writeln(".col184 dt {");
document.writeln("    background: url(\'./images/footer_icon.png\') no-repeat 0 -69px;");
document.writeln("}");
document.writeln(".col185 dt {");
document.writeln("    background: url(\'./images/footer_icon.png\') no-repeat 0 -92px;");
document.writeln("}");
document.writeln(".footer18 dd {");
document.writeln("    border-left: 1px dashed #A8A8A8;");
document.writeln("    padding-left: 20px;");
document.writeln("    height: 110px;");
document.writeln("    min-height: 110px;");
document.writeln("    margin: 15px 0 0 13px;");
document.writeln("}");
document.writeln(".footer18  a {");
document.writeln("    color: #575556;");
document.writeln("    line-height: 22px;");
document.writeln("    text-decoration: none;");
document.writeln("    outline: none;");
document.writeln("}");
document.writeln(".b-footer18 {");
document.writeln("    clear: both;");
document.writeln("    text-align: center;");
document.writeln("    padding: 60px 0 20px;");
document.writeln("    color: #008842;");
document.writeln("    font-size: 14px;");
document.writeln("}");
document.writeln(".last-footer18 {");
document.writeln("    clear: both;");
document.writeln("    color: #717171;");
document.writeln("    text-align: center;");
document.writeln("    line-height: 22px;");
document.writeln("    font-size: 12px;");
document.writeln("}");
document.writeln(".last-footer18 a {");
document.writeln("    color: #717171;");
document.writeln("    text-decoration: none;");
document.writeln("    outline: none;");
document.writeln("}");
document.writeln(".tail a {");
document.writeln("    display: inline-block;");
document.writeln("    position: relative;");
document.writeln("    margin: 0 10px;");
document.writeln("    zoom: 1;");
document.writeln("    vertical-align: middle;");
document.writeln("}");
document.writeln(".tail span {");
document.writeln("    height: 20px;");
document.writeln("    line-height: 20px;");
document.writeln("    margin: 0px 0px 0px 5px;");
document.writeln("    color: #939393;");
document.writeln("}");
document.writeln(".tail img {");
document.writeln("    height: 47px;");
document.writeln("}");
document.writeln(".tail a:last-child {");
document.writeln("    overflow: hidden;");
document.writeln("}");
document.writeln(".tail a:last-child img {");
document.writeln("    height: 20px;");
document.writeln("    float: left;");
document.writeln("}");
document.writeln(".tail a:last-child span {");
document.writeln("    float: left;");
document.writeln("}");
document.writeln(".H-line {");
document.writeln("    line-height: 22px;");
document.writeln("    color: #717171;");
document.writeln("}");
document.writeln(".footer18_list a:hover {");
document.writeln("    color: #008842;");
document.writeln("    text-decoration: underline;");
document.writeln("}");
document.writeln("</style>");
document.writeln("<body>");
document.writeln("    <div class=\'footer_service\'>");
document.writeln("        <div class=\'service\'>");
document.writeln("            <ul>");
document.writeln("                <li class=\'s181\'><b>全球精选</b><span>一站式生鲜购物方案</span></li>");
document.writeln("                <li class=\'s182\'><b>多仓直发</b><span>次日达配送服务</span></li>");
document.writeln("                <li class=\'s183\'><b>品质严选</b><span>精选正宗品质好食材</span></li>");
document.writeln("                <li class=\'s184\'><b>天天低价</b><span>会员专属优惠购不停</span></li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'footer18\'>");
document.writeln("        <div class=\'footer18_list\'>");
document.writeln("            <dl class=\'col181\'>");
document.writeln("                <dt>新手指南</dt>");
document.writeln("                <dd>");
document.writeln("                    <p><a href=\'qualification1.html\'>账户注册</a></p>");
document.writeln("                    <p><a href=\'qualification2.html\'>购物流程</a></p>");
document.writeln("                    <p><a href=\'qualification3.html\'>订购方式</a></p>");
document.writeln("                    <p><a href=\'qualification4.html\'>悠币说明</a></p>");
document.writeln("                    <p><a href=\'qualification5.html\'>会员等级</a><img src=\'http://img06.yiguoimg.com/e/web/170315/00941/154425/icon-new.png\' alt=\'\'></p>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'col182\'>");
document.writeln("                <dt>付款方式</dt>");
document.writeln("                <dd>");
document.writeln("                    <p><a href=\'qualification7.html\'>支付方式</a>/<a href=\'qualification8.html\'>发票说明</a></p>");
document.writeln("                    <p><a href=\'qualification10.html\'>礼品卡章程</a></p>");
document.writeln("                    <p><a href=\'qualification11.html\'>优惠代码</a></p>");
document.writeln("                    <p><a href=\'qualification12.html\'>卡券购买章程</a></p>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'col183\'>");
document.writeln("                <dt>配送方式</dt>");
document.writeln("                <dd>");
document.writeln("                    <p><a href=\'qualification13.html\'>配送运费</a></p>");
document.writeln("                    <p><a href=\'qualification14.html\'>时间及范围</a></p>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'col184\'>");
document.writeln("                <dt>售后服务</dt>");
document.writeln("                <dd>");
document.writeln("                    <p><a href=\'qualification16.html\'>退换货政策</a></p>");
document.writeln("                    <p><a href=\'qualification17.html\'>退换货流程</a></p>");
document.writeln("                    <p><a href=\'qualification18.html\'>常见问题</a></p>");
document.writeln("                    <p><a href=\'qualification19.html\'>极速退款</a></p>");
document.writeln("                    <p><a href=\'\'>投诉与建议</a></p>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("            <dl class=\'col185\'>");
document.writeln("                <dt>关于我们</dt>");
document.writeln("                <dd>");
document.writeln("                    <p><a href=\'qualification20.html\'>公司介绍</a></p>");
document.writeln("                    <p><a href=\'qualification21.html\'>联系我们</a></p>");
document.writeln("                    <p><a href=\'qualification22.html\'>业务合作</a></p>");
document.writeln("                    <p><a href=\'qualification23.html\'>诚信举报</a></p>");
document.writeln("                    <p><a href=\'qualification24.html\'>用户协议</a></p>");
document.writeln("                    <p><a href=\'qualification25.html\'>隐私协议</a></p>");
document.writeln("                    <p> <a href=\'qualification26.html\'>友情链接</a></p>");
document.writeln("                </dd>");
document.writeln("            </dl>");
document.writeln("        </div>");
document.writeln("        <div class=\'b-footer18\'>");
document.writeln("            <span>客服热线 400-000-7788 企业采购或团购，请转2号键咨询</span>");
document.writeln("            <span>周一至周日 9:00-21:00</span>");
document.writeln("        </div>");
document.writeln("        <div class=\'last-footer18\'>");
document.writeln("            <p class=\'H-line\'>所有图片均受著作权保护，未经许可任何单位与个人不得使用、复制、转载、摘编，违者必究法律责任。</p>");
document.writeln("            <p class=\'H-line\'><a href=\'javascript:void(0)\'>沪ICP备09008015号</a>  Copyright © 2005-2019 版权所有</p>");
document.writeln("            <p class=\'tail\'>");
document.writeln("                <a href=\'https://scjgj.sh.gov.cn/platform/survey/step1_phone\'><img src=\'http://img05.yiguoimg.com/d/web/190617/00191/142933/ordermeal.png\' alt=\'\'/></a>");
document.writeln("                <a href=\'http://www.shjbzx.cn\'><img src=\'http://img06.yiguoimg.com/d/web/190527/00191/172725/report.png\' alt=\'\'/></a>");
document.writeln("                <a href=\'http://www.shjbzx.cn\'><img src=\'http://img06.yiguoimg.com/d/web/190510/00192/161235/wxb.png\' alt=\'\'/></a>");
document.writeln("                <a href=\'javascript:void(0)\'><img src=\'http://img07.yiguoimg.com/d/web/171208/00652/173249/153685368061665897_121x29.png\' alt=\'\'/></a>");
document.writeln("                <a href=\'javascript:void(0)\'><img src=\'https://img05.yiguoimg.com/d/web/190618/00191/143543/962110.png\' alt=\'\'/></a>");
document.writeln("                <a href=\'javascript:void(0)\'><img src=\'http://img06.yiguoimg.com/d/web/181227/00281/143951/footer_copy.jpg\' alt=\'\'/></a>");
document.writeln("                <a href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=31010502000002\'><img src=\'http://www.beian.gov.cn/file/ghs.png\' alt=\'\'/><span>沪公网安备 31010502000002号</span></a>");
document.writeln("            </p>");
document.writeln("            <p class=\'H-line\'>违法和不良信息举报电话 400-000-7788</p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</body>");